在运行dw相关表之前，首先运行下面部分以创建中间表

In [1]:
import pandas as pd
from pyspark import SparkContext,SQLContext
from pyspark.sql import SQLContext
from pyspark.sql import SparkSession
from pyspark.sql.functions import udf, col
from pyspark.sql.types import StringType
import os
import sklearn
print(os.path.abspath(os.curdir))

/home/thd/人行征信

In [2]:
spark=SparkSession \
        .builder \
        .config("spark.eventLog.enabled", "false") \
        .config("spark.executor.memory", "8g")\
        .config("spark.driver.memory", "16g")\
        .config("spark.cores.max", "10")\
        .config("spark.task.maxFailures", "1000")\
        .config("spark.default.parallelism", "500")\
        .config("spark.sql.shuffle.partitions",100)\
        .appName('renhang_etl') \
        .master('yarn')\
        .getOrCreate()

In [3]:
#创建DW.dw_baseinfo_detail
table1 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRMESSAGEHEADER") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table1.createOrReplaceTempView("ICRMESSAGEHEADER")

table2 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRCREDITCUE") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table2.createOrReplaceTempView("ICRCREDITCUE")

table3 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRLOANCARDINFO") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table3.createOrReplaceTempView("ICRLOANCARDINFO")

table4 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRCREDITCUE") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table4.createOrReplaceTempView("ICRCREDITCUE")

table5 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRLATEST2YEAROVERDUECARD") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table5.createOrReplaceTempView("ICRLATEST2YEAROVERDUECARD")

table6 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRLATEST5YEAROVERDUEDETAIL") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table6.createOrReplaceTempView("ICRLATEST5YEAROVERDUEDETAIL")

table7 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRLATEST2YEAROVERDUE") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table7.createOrReplaceTempView("ICRLATEST2YEAROVERDUE")

table8 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRLOANINFO") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table8.createOrReplaceTempView("ICRLOANINFO")

table9 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRUNDESTORYLOANCARD") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table9.createOrReplaceTempView("ICRUNDESTORYLOANCARD")

table10 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRUNDESTORYSTANDARDLOANCARD") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table10.createOrReplaceTempView("ICRUNDESTORYSTANDARDLOANCARD")

table11 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRUNPAIDLOAN") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table11.createOrReplaceTempView("ICRUNPAIDLOAN")


table12 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICROVERDUESUMMARY") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table12.createOrReplaceTempView("ICROVERDUESUMMARY")


table13 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRFELLBACKSUMMARY") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table13.createOrReplaceTempView("ICRFELLBACKSUMMARY")


table14 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRGUARANTEE") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table14.createOrReplaceTempView("ICRGUARANTEE")


table15 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRGUARANTEESUMMARY") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table15.createOrReplaceTempView("ICRGUARANTEESUMMARY")


#######

table16 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRCIVILJUDGEMENT") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table16.createOrReplaceTempView("ICRCIVILJUDGEMENT")



table17 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRFORCEEXECUTION") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table17.createOrReplaceTempView("ICRFORCEEXECUTION")


table18 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRADMINPUNISHMENT") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table18.createOrReplaceTempView("ICRADMINPUNISHMENT")


table19 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRTAXARREAR") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table19.createOrReplaceTempView("ICRTAXARREAR")


table20 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRACCFUND") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table20.createOrReplaceTempView("ICRACCFUND")



table21 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRENDOWMENTINSURANCEDEPOSIT") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table21.createOrReplaceTempView("ICRENDOWMENTINSURANCEDEPOSIT")


table22 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRRECORDDETAIL") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table22.createOrReplaceTempView("ICRRECORDDETAIL")



table23 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRRECORDDETAIL") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table23.createOrReplaceTempView("ICRRECORDDETAIL")


table24 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.QUERY_HISTORY") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table24.createOrReplaceTempView("QUERY_HISTORY")

table25 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "hyxf.ICRRECORDSUMMARY") \
    .option("user", "dt") \
    .option("password", "Usd&212%wePO2") \
    .load()
table25.createOrReplaceTempView("ICRRECORDSUMMARY")

In [4]:
spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		case 
			when ordue.LASTMONTHS in ('G','Z','D') then 8 
			else ordue.LASTMONTHS 
		end as LASTMONTHS ,
		loanfo.GUARANTEETYPE,STATE,FINANCEORG
from ICRLATEST2YEAROVERDUECARD ordue
-- 只取贷记卡的信息
inner join ICRLOANCARDINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where BIZTYPE='准贷记卡' and ordue.LASTMONTHS!='C'
""").createOrReplaceTempView("temp_standcard_2yearoverdue")


spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		case 
			when ordue.LASTMONTHS in ('G','Z','D') then 8 
			else ordue.LASTMONTHS 
		end as LASTMONTHS ,
		loanfo.GUARANTEETYPE,STATE,FINANCEORG
from ICRLATEST2YEAROVERDUECARD ordue
-- 只取贷记卡的信息
inner join ICRLOANCARDINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where BIZTYPE='贷记卡' and ordue.LASTMONTHS!='C'
""").createOrReplaceTempView("temp_creditcard_2yearoverdue")


spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		ordue.LASTMONTHS,ordue.AMOUNT,loanfo.GUARANTEETYPE,STATE,FINANCEORG
from ICRLATEST5YEAROVERDUEDETAIL ordue
-- 只取贷记卡的信息
inner join ICRLOANCARDINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where month!='--'  and BIZTYPE='贷记卡'
""").createOrReplaceTempView("temp_creditcard_overdue")


spark.sql("""
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
		MONTH,
		gap_months,
		LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_creditcard_2yearoverdue
union 
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
		date_format(concat(month,'.01'),'%Y-%m'),
        gap_months,
		LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_creditcard_overdue
""").createOrReplaceTempView("temp_creditcard_5yearoverdue")



spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		case 
			when ordue.LASTMONTHS in ('G','Z','D') then 8 
			else ordue.LASTMONTHS 
		end as LASTMONTHS ,
		loanfo.GUARANTEETYPE,
		STATE,
		FINANCEORG
from ICRLATEST2YEAROVERDUE ordue
-- 只取贷款的信息
inner join ICRLOANINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where ordue.LASTMONTHS!='C'
""").createOrReplaceTempView("temp_loan_2yearoverdue")



spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		ordue.LASTMONTHS,
		ordue.AMOUNT,
		loanfo.GUARANTEETYPE,
		STATE,FINANCEORG
from ICRLATEST5YEAROVERDUEDETAIL ordue
-- 只取贷款的信息
inner join ICRLOANINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where month!='--'
""").createOrReplaceTempView("temp_loan_overdue")




spark.sql("""
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
        MONTH,
		gap_months,
		LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_loan_2yearoverdue
union 
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
		date_format(concat(month,'.01'),'%Y-%m'),gap_months,LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_loan_overdue
""").createOrReplaceTempView("temp_loan_5yearoverdue")

中间表已运行完成，spark sql 创建所需要的表

In [5]:
spark.sql("""


select head.reportno,
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_acct_num,0) end as curovd_scard_acct_num,
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_org_num,0) end as curovd_scard_org_num,	
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_amount,0) end as curovd_scard_amount,		
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_max,0) end as curovd_scard_max,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_account_num,0) end as curused_scard_account_num,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_org_num,0) end as curused_scard_org_num,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_amount,0) end as curused_scard_amount,		
case when scard.reportno is null then -9999999
	else nvl(sovdm.scard_latest_ovdue_months,-9999998) end as scard_latest_ovdue_months,	
-- 最大逾期期数	
case when scard.reportno is null then -9999999
	else nvl(latest3mon_scard_max_ovd,0) end as latest3mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_scard_max_ovd,0) end as latest6mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_scard_max_ovd,0) end as latest9mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_scard_max_ovd,0) end as latest12mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_scard_max_ovd,0) end as latest18mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_scard_max_ovd,0) end as latest24mon_scard_max_ovd,
	
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_acct_num,0) end as latest3mon_ovd_scard_acct_num,
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_org_num,0) end as latest3mon_ovd_scard_org_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_moth_num,0) end as latest3mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_num,0) end as latest3mon_ovd_scard_num,		
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd2m_scardaccount_num,0) end as latest3mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd2m_scard_num,0) end as latest3mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd3m_scardaccount_num,0) end as latest3mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd3m_scard_num,0) end as latest3mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd4m_scardaccount_num,0) end as latest3mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd4m_scard_num,0) end as latest3mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_acct_num,0) end as latest6mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_org_num,0) end as latest6mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_moth_num,0) end as latest6mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_num,0) end as latest6mon_ovd_scard_num,		
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd2m_scardaccount_num,0) end as latest6mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd2m_scard_num,0) end as latest6mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd3m_scardaccount_num,0) end as latest6mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd3m_scard_num,0) end as latest6mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd4m_scardaccount_num,0) end as latest6mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd4m_scard_num,0) end as latest6mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_acct_num,0) end as latest9mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_org_num,0) end as latest9mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_moth_num,0) end as latest9mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_num,0) end as latest9mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd2m_scardaccount_num,0) end as latest9mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd2m_scard_num,0) end as latest9mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd3m_scardaccount_num,0) end as latest9mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd3m_scard_num,0) end as latest9mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd4m_scardaccount_num,0) end as latest9mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd4m_scard_num,0) end as latest9mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_acct_num,0) end as latest12mon_ovd_scard_acct_num,		
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd_scard_org_num,0) end as latest12mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_moth_num,0) end as latest12mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_num,0) end as latest12mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd2m_scardaccount_num,0) end as latest12mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd2m_scard_num,0) end as latest12mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd3m_scardaccount_num,0) end as latest12mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd3m_scard_num,0) end as latest12mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd4m_scardaccount_num,0) end as latest12mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd4m_scard_num,0) end as latest12mon_ovd4m_scard_num,	
					
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_acct_num,0) end as latest18mon_ovd_scard_acct_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_org_num,0) end as latest18mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_moth_num,0) end as latest18mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_num,0) end as latest18mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd2m_scardaccount_num,0) end as latest18mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd2m_scard_num,0) end as latest18mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd3m_scardaccount_num,0) end as latest18mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd3m_scard_num,0) end as latest18mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd4m_scardaccount_num,0) end as latest18mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd4m_scard_num,0) end as latest18mon_ovd4m_scard_num,		
	
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_acct_num,0) end as latest24mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 	
	else nvl(latest24mon_ovd_scard_org_num,0) end as latest24mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_moth_num,0) end as latest24mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_num,0) end as latest24mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd2m_scardaccount_num,0) end as latest24mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd2m_scard_num,0) end as latest24mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd3m_scardaccount_num,0) end as latest24mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd3m_scard_num,0) end as latest24mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd4m_scardaccount_num,0) end as latest24mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd4m_scard_num,0) end as latest24mon_ovd4m_scard_num,
now(),now(),now()	
		
from ICRMESSAGEHEADER head
left JOIN
(-- 当前处于逾期的贷记卡
select reportno,count(distinct account) as curovd_scard_acct_num,
	count(distinct FINANCEORG) as curovd_scard_org_num,
	sum(nvl(CURROVERDUEAMOUNT,0)) as curovd_scard_amount,
	max(case when substr(LATEST24STATE,-1) in ('G','Z','D') then 8 
		else substr(LATEST24STATE,-1) end) as curovd_scard_max
from ICRLOANCARDINFO 
where biztype='准贷记卡' and LATEST24STATE is not null and substr(LATEST24STATE,-1) not in('/', '#', 'N', '*','C')
group by reportno
) scfo on head.reportno=scfo.reportno
-- 当前有透支余额的准贷记卡
left join
(
select reportno,count(distinct account) as curused_scard_account_num,
	count(distinct FINANCEORG) as curused_scard_org_num,
	sum(nvl(USEDCREDITLIMITAMOUNT,0)) as curused_scard_amount
from ICRLOANCARDINFO 
where biztype='准贷记卡' and USEDCREDITLIMITAMOUNT>0 and USEDCREDITLIMITAMOUNT is not null
group by reportno
) curused on head.reportno=curused.reportno
-- 准贷记卡最近一次逾期距今月份数
left join
(
select reportno,min(nvl(gap_months,0)) as scard_latest_ovdue_months
from temp_standcard_2yearoverdue 
group by reportno
) sovdm on head.reportno=sovdm.reportno
-- 准贷记卡
left join 
(select distinct reportno from ICRLOANCARDINFO
	where biztype='准贷记卡' 
)scard  on head.reportno=scard.reportno
left join
(
	select reportno,
	-- 账户
	nvl(count(distinct latest3mon_ovd_scard_acct_num),0) as latest3mon_ovd_scard_acct_num,
	nvl(count(distinct latest6mon_ovd_scard_acct_num),0) as latest6mon_ovd_scard_acct_num,
	nvl(count(distinct latest9mon_ovd_scard_acct_num),0) as latest9mon_ovd_scard_acct_num,
	nvl(count(distinct latest12mon_ovd_scard_acct_num),0) as latest12mon_ovd_scard_acct_num,
	nvl(count(distinct latest18mon_ovd_scard_acct_num),0) as latest18mon_ovd_scard_acct_num,
	nvl(count(distinct latest24mon_ovd_scard_acct_num),0) as latest24mon_ovd_scard_acct_num,
	-- 机构
	nvl(count(distinct latest3mon_ovd_scard_org_num),0) as latest3mon_ovd_scard_org_num,
	nvl(count(distinct latest6mon_ovd_scard_org_num),0) as latest6mon_ovd_scard_org_num,
	nvl(count(distinct latest9mon_ovd_scard_org_num),0) as latest9mon_ovd_scard_org_num,
	nvl(count(distinct latest12mon_ovd_scard_org_num),0) as latest12mon_ovd_scard_org_num,
	nvl(count(distinct latest18mon_ovd_scard_org_num),0) as latest18mon_ovd_scard_org_num,
	nvl(count(distinct latest24mon_ovd_scard_org_num),0) as latest24mon_ovd_scard_org_num,
	-- 月份数
	nvl(count( distinct latest3mon_ovd_scard_moth_num),0) as latest3mon_ovd_scard_moth_num,
	nvl(count( distinct latest6mon_ovd_scard_moth_num),0) as latest6mon_ovd_scard_moth_num,
	nvl(count( distinct latest9mon_ovd_scard_moth_num),0) as latest9mon_ovd_scard_moth_num,
	nvl(count( distinct latest12mon_ovd_scard_moth_num),0) as latest12mon_ovd_scard_moth_num,
	nvl(count( distinct latest18mon_ovd_scard_moth_num),0) as latest18mon_ovd_scard_moth_num,
	nvl(count( distinct latest24mon_ovd_scard_moth_num),0) as latest24mon_ovd_scard_moth_num,
	-- 次数
	sum(latest3mon_ovd_scard_num) as latest3mon_ovd_scard_num,
	sum(latest6mon_ovd_scard_num) as latest6mon_ovd_scard_num,
	sum(latest9mon_ovd_scard_num) as latest9mon_ovd_scard_num,
	sum(latest12mon_ovd_scard_num) as latest12mon_ovd_scard_num,
	sum(latest18mon_ovd_scard_num) as latest18mon_ovd_scard_num,
	sum(latest24mon_ovd_scard_num) as latest24mon_ovd_scard_num,
	-- 最大逾期期数  
	max(nvl(latest3mon_scard_max_ovd,0)) as latest3mon_scard_max_ovd,
	max(nvl(latest6mon_scard_max_ovd,0)) as latest6mon_scard_max_ovd,
	max(nvl(latest9mon_scard_max_ovd,0)) as latest9mon_scard_max_ovd,
	max(nvl(latest12mon_scard_max_ovd,0)) as latest12mon_scard_max_ovd,
	max(nvl(latest18mon_scard_max_ovd,0)) as latest18mon_scard_max_ovd,
	max(nvl(latest24mon_scard_max_ovd,0)) as latest24mon_scard_max_ovd,
	
	nvl(count(distinct latest3mon_ovd2m_scardaccount_num),0) as latest3mon_ovd2m_scardaccount_num,
	nvl(sum(latest3mon_ovd2m_scard_num),0) as latest3mon_ovd2m_scard_num,
	nvl(count(distinct latest3mon_ovd3m_scardaccount_num),0) as latest3mon_ovd3m_scardaccount_num,
	nvl(sum(latest3mon_ovd3m_scard_num),0) as latest3mon_ovd3m_scard_num,
	nvl(count(distinct latest3mon_ovd4m_scardaccount_num),0) as latest3mon_ovd4m_scardaccount_num,
	nvl(sum(latest3mon_ovd4m_scard_num),0) as latest3mon_ovd4m_scard_num,
	
	nvl(count(distinct latest6mon_ovd2m_scardaccount_num),0) as latest6mon_ovd2m_scardaccount_num,
	nvl(sum(latest6mon_ovd2m_scard_num),0) as latest6mon_ovd2m_scard_num,
	nvl(count(distinct latest6mon_ovd3m_scardaccount_num),0) as latest6mon_ovd3m_scardaccount_num,
	nvl(sum(latest6mon_ovd3m_scard_num),0) as latest6mon_ovd3m_scard_num,
	nvl(count(distinct latest6mon_ovd4m_scardaccount_num),0) as latest6mon_ovd4m_scardaccount_num,
	nvl(sum(latest6mon_ovd4m_scard_num),0) as latest6mon_ovd4m_scard_num,
	
	nvl(count(distinct latest9mon_ovd2m_scardaccount_num),0) as latest9mon_ovd2m_scardaccount_num,
	nvl(sum(latest9mon_ovd2m_scard_num),0) as latest9mon_ovd2m_scard_num,
	nvl(count(distinct latest9mon_ovd3m_scardaccount_num),0) as latest9mon_ovd3m_scardaccount_num,
	nvl(sum(latest9mon_ovd3m_scard_num),0) as latest9mon_ovd3m_scard_num,
	nvl(count(distinct latest9mon_ovd4m_scardaccount_num),0) as latest9mon_ovd4m_scardaccount_num,
	nvl(sum(latest9mon_ovd4m_scard_num),0) as latest9mon_ovd4m_scard_num,
	
	nvl(count(distinct latest12mon_ovd2m_scardaccount_num),0) as latest12mon_ovd2m_scardaccount_num,
	nvl(sum(latest12mon_ovd2m_scard_num),0) as latest12mon_ovd2m_scard_num,
	nvl(count(distinct latest12mon_ovd3m_scardaccount_num),0) as latest12mon_ovd3m_scardaccount_num,
	nvl(sum(latest12mon_ovd3m_scard_num),0) as latest12mon_ovd3m_scard_num,
	nvl(count(distinct latest12mon_ovd4m_scardaccount_num),0) as latest12mon_ovd4m_scardaccount_num,
	nvl(sum(latest12mon_ovd4m_scard_num),0) as latest12mon_ovd4m_scard_num,
	
	nvl(count(distinct latest18mon_ovd2m_scardaccount_num),0) as latest18mon_ovd2m_scardaccount_num,
	nvl(sum(latest18mon_ovd2m_scard_num),0) as latest18mon_ovd2m_scard_num,
	nvl(count(distinct latest18mon_ovd3m_scardaccount_num),0) as latest18mon_ovd3m_scardaccount_num,
	nvl(sum(latest18mon_ovd3m_scard_num),0) as latest18mon_ovd3m_scard_num,
	nvl(count(distinct latest18mon_ovd4m_scardaccount_num),0) as latest18mon_ovd4m_scardaccount_num,
	nvl(sum(latest18mon_ovd4m_scard_num),0) as latest18mon_ovd4m_scard_num,
	
	nvl(count(distinct latest24mon_ovd2m_scardaccount_num),0) as latest24mon_ovd2m_scardaccount_num,
	nvl(sum(latest24mon_ovd2m_scard_num),0) as latest24mon_ovd2m_scard_num,
	nvl(count(distinct latest24mon_ovd3m_scardaccount_num),0) as latest24mon_ovd3m_scardaccount_num,
	nvl(sum(latest24mon_ovd3m_scard_num),0) as latest24mon_ovd3m_scard_num,
	nvl(count(distinct latest24mon_ovd4m_scardaccount_num),0) as latest24mon_ovd4m_scardaccount_num,
	nvl(sum(latest24mon_ovd4m_scard_num),0) as latest24mon_ovd4m_scard_num

	from (
		select
			reportno,
			-- 账户
			case when gap_months<3 then account else null end as latest3mon_ovd_scard_acct_num,
			case when gap_months<6 then account else null end as latest6mon_ovd_scard_acct_num,
			case when gap_months<9 then account else null end as latest9mon_ovd_scard_acct_num,
			case when gap_months<12 then account else null end as latest12mon_ovd_scard_acct_num,
			case when gap_months<18 then account else null end as latest18mon_ovd_scard_acct_num,
			case when gap_months<24 then account else null end as latest24mon_ovd_scard_acct_num,
			-- 机构
			case when gap_months<3 then FINANCEORG else null end as latest3mon_ovd_scard_org_num,
			case when gap_months<6 then FINANCEORG else null end as latest6mon_ovd_scard_org_num,
			case when gap_months<9 then FINANCEORG else null end as latest9mon_ovd_scard_org_num,
			case when gap_months<12 then FINANCEORG else null end as latest12mon_ovd_scard_org_num,
			case when gap_months<18 then FINANCEORG else null end as latest18mon_ovd_scard_org_num,
			case when gap_months<24 then FINANCEORG else null end as latest24mon_ovd_scard_org_num,
			-- 月份数
			case when gap_months<3 then month else null end as latest3mon_ovd_scard_moth_num,
			case when gap_months<6 then month else null end as latest6mon_ovd_scard_moth_num,
			case when gap_months<9 then month else null end as latest9mon_ovd_scard_moth_num,	
			case when gap_months<12 then month else null end as latest12mon_ovd_scard_moth_num,
			case when gap_months<18 then month else null end as latest18mon_ovd_scard_moth_num,	
			case when gap_months<24 then month else null end as latest24mon_ovd_scard_moth_num,
			-- 次数
			case when gap_months<3 then 1 else 0 end as latest3mon_ovd_scard_num,
			case when gap_months<6 then 1 else 0 end as latest6mon_ovd_scard_num,		
			case when gap_months<9 then 1 else 0 end as latest9mon_ovd_scard_num,		
			case when gap_months<12 then 1 else 0 end as latest12mon_ovd_scard_num,		
			case when gap_months<18 then 1 else 0 end as latest18mon_ovd_scard_num,		
			case when gap_months<24 then 1 else 0 end as latest24mon_ovd_scard_num,
			-- 最大逾期期数
			case when gap_months<3 then LASTMONTHS else null end as latest3mon_scard_max_ovd,
			case when gap_months<6 then LASTMONTHS else null end as latest6mon_scard_max_ovd,
			case when gap_months<9 then LASTMONTHS else null end as latest9mon_scard_max_ovd,
			case when gap_months<12 then LASTMONTHS else null end as latest12mon_scard_max_ovd,
			case when gap_months<18 then LASTMONTHS else null end as latest18mon_scard_max_ovd,
			case when gap_months<24 then LASTMONTHS else null end as latest24mon_scard_max_ovd,
			
			case when gap_months<3 and LASTMONTHS>=2  then account else null end as latest3mon_ovd2m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>=2  then 1 else 0 end as latest3mon_ovd2m_scard_num,
			case when gap_months<3 and LASTMONTHS>=3  then account else null end as latest3mon_ovd3m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>=3  then 1 else 0 end as latest3mon_ovd3m_scard_num,
			case when gap_months<3 and LASTMONTHS>3  then account else null end as latest3mon_ovd4m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>3  then 1 else 0 end as latest3mon_ovd4m_scard_num,
			
			case when gap_months<6 and LASTMONTHS>=2  then account else null end as latest6mon_ovd2m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>=2  then 1 else 0 end as latest6mon_ovd2m_scard_num,
			case when gap_months<6 and LASTMONTHS>=3  then account else null end as latest6mon_ovd3m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>=3  then 1 else 0 end as latest6mon_ovd3m_scard_num,
			case when gap_months<6 and LASTMONTHS>3  then account else null end as latest6mon_ovd4m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>3  then 1 else 0 end as latest6mon_ovd4m_scard_num,
	
			case when gap_months<9 and LASTMONTHS>=2  then account else null end as latest9mon_ovd2m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>=2  then 1 else 0 end as latest9mon_ovd2m_scard_num,
			case when gap_months<9 and LASTMONTHS>=3  then account else null end as latest9mon_ovd3m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>=3  then 1 else 0 end as latest9mon_ovd3m_scard_num,
			case when gap_months<9 and LASTMONTHS>3  then account else null end as latest9mon_ovd4m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>3  then 1 else 0 end as latest9mon_ovd4m_scard_num,
	
			case when gap_months<12 and LASTMONTHS>=2  then account else null end as latest12mon_ovd2m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>=2  then 1 else 0 end as latest12mon_ovd2m_scard_num,
			case when gap_months<12 and LASTMONTHS>=3  then account else null end as latest12mon_ovd3m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>=3  then 1 else 0 end as latest12mon_ovd3m_scard_num,
			case when gap_months<12 and LASTMONTHS>3  then account else null end as latest12mon_ovd4m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>3  then 1 else 0 end as latest12mon_ovd4m_scard_num,		
	
			case when gap_months<18 and LASTMONTHS>=2  then account else null end as latest18mon_ovd2m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>=2  then 1 else 0 end as latest18mon_ovd2m_scard_num,
			case when gap_months<18 and LASTMONTHS>=3  then account else null end as latest18mon_ovd3m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>=3  then 1 else 0 end as latest18mon_ovd3m_scard_num,
			case when gap_months<18 and LASTMONTHS>3  then account else null end as latest18mon_ovd4m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>3  then 1 else 0 end as latest18mon_ovd4m_scard_num,
	
			case when gap_months<24 and LASTMONTHS>=2  then account else null end as latest24mon_ovd2m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>=2  then 1 else 0 end as latest24mon_ovd2m_scard_num,
			case when gap_months<24 and LASTMONTHS>=3  then account else null end as latest24mon_ovd3m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>=3  then 1 else 0 end as latest24mon_ovd3m_scard_num,
			case when gap_months<24 and LASTMONTHS>3  then account else null end as latest24mon_ovd4m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>3  then 1 else 0 end as latest24mon_ovd4m_scard_num
			
		from temp_standcard_2yearoverdue
	)t
	group by reportno
)ovd on head.reportno=ovd.reportno


""").createOrReplaceTempView("dw_stdcard_overdue_summary")

In [6]:
spark.sql("""

select 
	distinct REPORTNO,
	account,
	month,
	gap_months,
	row_number() over (partition by REPORTNO order by REPORTNO,month,account ) as rownum

from temp_standcard_2yearoverdue
where gap_months<24
order by REPORTNO,month,account

""").createOrReplaceTempView("temp_scard_cont_1")


spark.sql("""

select 
	reportno,
	account,
	month,
	gap_months,
	rownum,
 	add_months(date_format(concat(month,'-01'),'%Y-%m-%d'),  -1*rownum ) as timeadd
from temp_scard_cont_1


""").createOrReplaceTempView("temp_scard_cont_2")




spark.sql("""

select head.reportno,
	case when scard.reportno is null then -9999999
		else ifnull(m3.mth3_scard_overdue_maxmonth,0) end as mth3_scard_overdue_maxmonth,
	case when scard.reportno is null then -9999999
		else ifnull(m6.mth6_scard_overdue_maxmonth,0) end as mth6_scard_overdue_maxmonth,
	case when scard.reportno is null then -9999999
		else ifnull(m9.mth9_scard_overdue_maxmonth,0) end as mth9_scard_overdue_maxmonth,
	case when scard.reportno is null then -9999999
		else ifnull(m12.mth12_scard_overdue_maxmonth,0) end as mth12_scard_overdue_maxmonth,
	case when scard.reportno is null then -9999999
		else ifnull(m18.mth18_scard_overdue_maxmonth,0) end as mth18_scard_overdue_maxmonth,
	case when scard.reportno is null then -9999999
		else ifnull(m24.mth24_scard_overdue_maxmonth,0) end as mth24_scard_overdue_maxmonth,
	now(),now(),now()
from ICRMESSAGEHEADER head
left join 
(select reportno,max(cont_mons) as mth3_scard_overdue_maxmonth
from (
	select reportno,account,count(*) as cont_mons
	from temp_scard_cont_2
	where gap_months<3
	group by reportno,account,timeadd
	)t
group by reportno	
)m3 on head.reportno=m3.reportno
left join 
(select reportno,max(cont_mons) as mth6_scard_overdue_maxmonth
from (
	select reportno,account,count(*) as cont_mons
	from temp_scard_cont_2
	where gap_months<6
	group by reportno,account,timeadd
	)t
group by reportno	
)m6 on head.reportno=m6.reportno
left join 
(select reportno,max(cont_mons) as mth9_scard_overdue_maxmonth
from (
	select reportno,account,count(*) as cont_mons
	from temp_scard_cont_2
	where gap_months<9
	group by reportno,account,timeadd
	)t
group by reportno	
)m9 on head.reportno=m9.reportno
left join 
(select reportno,max(cont_mons) as mth12_scard_overdue_maxmonth
from (
	select reportno,account,count(*) as cont_mons
	from temp_scard_cont_2
	where gap_months<12
	group by reportno,account,timeadd
	)t
group by reportno	
)m12 on head.reportno=m12.reportno
left join 
(select reportno,max(cont_mons) as mth18_scard_overdue_maxmonth
from (
	select reportno,account,count(*) as cont_mons
	from temp_scard_cont_2
	where gap_months<18
	group by reportno,account,timeadd
	)t
group by reportno	
)m18 on head.reportno=m18.reportno
left join 
(select reportno,max(cont_mons) as mth24_scard_overdue_maxmonth
from (
	select reportno,account,count(*) as cont_mons
	from temp_scard_cont_2
	where gap_months<24
	group by reportno,account,timeadd
	)t
group by reportno	
)m24 on head.reportno=m24.reportno
left join 
(select distinct reportno from ICRLOANCARDINFO
	where biztype='准贷记卡'
)scard  on head.reportno=scard.reportno

""").createOrReplaceTempView("dw_scard_contiue_overdue")

In [7]:
spark.sql("""

select 
		ovdue.reportno,
		case 
			when loan.all_loan_account is null then -9999999
			when loan.all_loan_account is not null and ovdue1.overdue_loan_account_num is null then 0
			else ovdue1.overdue_loan_account_num 
		end as overdue_loan_account_num,
		case 
			when loan.all_loan_account=0 or loan.all_loan_account is null then -9999998 
			when (loan.all_loan_account!=0 and loan.all_loan_account is not null) and ovdue1.overdue_loan_account_num is null then 0
			else round(ovdue1.overdue_loan_account_num/loan.all_loan_account,5)  
		end as overdue_loan_account_percent,
		case 
			when loan.all_loan_account is null then -9999999
			when loan.all_loan_account is not null and ovdue1.overdue_loan_account_num is null then 0
			else loanbal.overdue_loan_account_balance 
		end as overdue_loan_account_balance,
		case 
			when loan_sum=0 or loan.loan_sum is null then -9999998
			when loan_sum!=0 and loan.loan_sum is not null and ovdue1.overdue_loan_account_num is null then 0
			else round(loanbal.overdue_loan_account_balance/loan_sum,5) 
		end as overdue_loan_balance_percent,
		nvl(sumy.highest_loan_overdue_permon,-9999999) as highest_loan_overdue_permon,
		nvl(sumy.highest_ccard_overdue_permon,-9999999) as highest_ccard_overdue_permon,
		nvl(sumy.highest_scard_overdue_permon,-9999999) as highest_scard_overdue_permon,
		nvl(sumy.max_loan_duration,-9999999) as max_loan_duration,
		nvl(sumy.max_ccard_duration,-9999999) as max_ccard_duration,
		nvl(sumy.max_scard_duration,-9999999) as max_scard_duration,
		case 
			when loan.all_loan_account is null then -9999999
			when loan.all_loan_account is not null and ovdue1.reportno is null then nvl(sumy.loan_longest_month,0)
			else lmon.loan_overdue_months 
		end as loan_overdue_months,
		case 
			when ccard.reportno is null then -9999999
			when ccard.reportno is not null and cmon.reportno is null then nvl(sumy.ccard_longest_month,0)
			else cmon.ccard_overdue_months 
		end as ccard_overdue_months,
		case 
			when scard.reportno is null then -9999999
			when scard.reportno is not null and smon.reportno is null then nvl(sumy.scard_longest_month,0)
			else smon.scard_overdue_months 
		end as scard_overdue_months,	
		case 
			when loan.all_loan_account is null then -9999999
			when loanfo.reportno is null and loan.all_loan_account is not null then 0
			else loanfo.curoverdue_loan_num 
		end as curoverdue_loan_num,
		case 
			when loan.all_loan_account is null then -9999999
			when loanfo.reportno is null and loan.all_loan_account is not null then 0
			else loanfo.curoverdue_loan_amount 
		end as curoverdue_loan_amount,
		case 
			when loan.all_loan_account is null then -9999999
			when loanfo.reportno is null and loan.all_loan_account is not null then 0
			else loanfo.curoverdue_longest_months 
		end as curoverdue_longest_months,
		case 
			when loan.all_loan_account is null then -9999999
			when loanfo.reportno is null and loan.all_loan_account is not null then 0
			else loanfo.curoverdue_org_num 
		end as curoverdue_org_num,	
		case 
			when ccard.reportno is null then -9999999
			when ccard.reportno is not null and cdtod.reportno is null then 0
			else cdtod.curoverdue_creditcard_account_num 
		end as curoverdue_creditcard_account_num,
		case 
			when ccard.reportno is null then -9999999
			when ccard.reportno is not null and cdtod.reportno is null then 0
			else cdtod.curoverdue_creditcard_org_num 
		end as curoverdue_creditcard_org_num,
		case 
			when ccard.reportno is null then -9999999
			when ccard.reportno is not null and cdtod.reportno is null then 0
			else cdtod.curoverdue_creditcard_amount 
		end as curoverdue_creditcard_amount,	
		case 
			when ccard.reportno is null then -9999999
			when ccard.reportno is not null and cdtod.reportno is null then 0
			else cdtod.curoverdue_creditcard_max 
		end as curoverdue_creditcard_max,
		now(),
		now(),
		now()
from 
(
	select 
		distinct reportno 
	from ICRMESSAGEHEADER
) ovdue
left join 
(-- 发生过逾期的贷款账户笔数
	select 
		a.reportno,
		count(distinct a.account) as overdue_loan_account_num
	from temp_loan_5yearoverdue a
	group by a.reportno
) ovdue1 on ovdue.reportno=ovdue1.reportno
-- 贷款总笔数、贷款总余额
left join 
(
	select 
		reportno,
		count(*) as all_loan_account,
		sum(nvl(BALANCE,0)) as loan_sum
	from ICRLOANINFO
	group by reportno
) loan on ovdue.reportno=loan.reportno
left join 
(	-- 发生过逾期的贷款账户余额
	select 
		a.reportno,
		sum(nvl(b.BALANCE,0)) as overdue_loan_account_balance
	from (
		select 
			distinct reportno,
			account
		from temp_loan_5yearoverdue 
		)a
	left join ICRLOANINFO b on a.reportno=b.reportno and a.account=b.account
	group by a.reportno
)loanbal on ovdue.reportno=loanbal.reportno
left JOIN
(-- 贷款、贷记卡、准贷记卡单月最高逾期金额/最长逾期月数
select 
		reportno,
		HIGHESTOVERDUEAMOUNTPERMON as highest_loan_overdue_permon,
		HIGHESTOVERDUEAMOUNTPERMON2 as highest_ccard_overdue_permon,
		HIGHESTOVERDUEAMOUNTPERMON3 as highest_scard_overdue_permon,
		MAXDURATION as max_loan_duration,
		MAXDURATION2 as max_ccard_duration,
		MAXDURATION3 as max_scard_duration,
		MONTHS3 as scard_longest_month,
		MONTHS2 as ccard_longest_month,
		MONTHS as loan_longest_month
from ICROVERDUESUMMARY
)sumy on ovdue.reportno=sumy.reportno
-- 贷款发生过逾期的月份数
left join
(	
	select 
		reportno,
		count(distinct month) as loan_overdue_months
	from temp_loan_5yearoverdue
	group by reportno
)lmon on ovdue.reportno=lmon.reportno
-- 贷记卡发生过逾期的月份数
left join
(	select 
		reportno,
		count(distinct month) as ccard_overdue_months
	from temp_creditcard_5yearoverdue
	group by reportno
)cmon on ovdue.reportno=cmon.reportno
-- 准贷记卡发生过逾期的月份数
left join
(	select 
		reportno,
		count(distinct month) as scard_overdue_months
	from temp_standcard_2yearoverdue
	group by reportno
)smon on ovdue.reportno=smon.reportno

left JOIN
(-- 当前处于逾期的贷款
select 
	reportno,
	count(*) as curoverdue_loan_num,
	sum(nvl(CURROVERDUEAMOUNT,0)) as curoverdue_loan_amount,
	count(distinct FINANCEORG) as curoverdue_org_num,
	max(case when substr(LATEST24STATE,-1) in ('G','Z','D') then 8 
		else substr(LATEST24STATE,-1) end) as curoverdue_longest_months
from ICRLOANINFO 
where LATEST24STATE is not null and substr(LATEST24STATE,-1) not in('/', '#', 'N', '*','C')
group by reportno
) loanfo on ovdue.reportno=loanfo.reportno
/*
-- 当前贷款最长逾期期数
left join
(select reportno,max(LASTMONTHS) as curoverdue_longest_months 
from DW.temp_loan_5yearoverdue
group by reportno
)loan1 on ovdue.reportno=loan1.reportno
*/
-- 当前处于逾期的贷记卡
left join 
(	
	select 
		reportno,
		count(distinct  ACCOUNT) as curoverdue_creditcard_account_num,
		count(distinct FINANCEORG) as curoverdue_creditcard_org_num,
		sum(nvl(CURROVERDUEAMOUNT,0)) as curoverdue_creditcard_amount,
		max(substr(LATEST24STATE,-1)) as curoverdue_creditcard_max
	
	from ICRLOANCARDINFO
	where LATEST24STATE is not null and substr(LATEST24STATE,-1) not in('/', '#', 'N', '*','C')
		and biztype='贷记卡'
	group by reportno
) cdtod on ovdue.reportno=cdtod.reportno
left join 
(	select reportno,count(*)  as ccard_num 
	from ICRLOANCARDINFO
	where biztype='贷记卡'
	group by reportno
)ccard on ovdue.reportno=ccard.reportno
left join 
(	select reportno,count(*)  as scard_num 
	from ICRLOANCARDINFO
	where biztype='准贷记卡'
	group by reportno
)scard on ovdue.reportno=scard.reportno



""").createOrReplaceTempView("dw_overdue_account")

In [8]:
spark.sql("""

select t1.reportno,t1.curovd_scard_acct_num	as	curovd_scard_acct_num
,t1.curovd_scard_org_num	as	curovd_scard_org_num
,t1.curovd_scard_amount	as	curovd_scard_amount
,t1.curovd_scard_max	as	curovd_scard_max
,t1.curused_scard_account_num	as	curused_scard_account_num
,t1.curused_scard_org_num	as	curused_scard_org_num
,t1.curused_scard_amount	as	curused_scard_amount
,t1.scard_latest_ovdue_months	as	scard_latest_ovdue_months
,t1.latest3mon_scard_max_ovd	as	ltst3mon_scard_max_ovd
,t1.latest6mon_scard_max_ovd	as	ltst6mon_scard_max_ovd
,t1.latest9mon_scard_max_ovd	as	ltst9mon_scard_max_ovd
,t1.latest12mon_scard_max_ovd	as	ltst12mon_scard_max_ovd
,t1.latest18mon_scard_max_ovd	as	ltst18mon_scard_max_ovd
,t1.latest24mon_scard_max_ovd	as	ltst24mon_scard_max_ovd
,t1.latest3mon_ovd_scard_acct_num	as	ltst3mon_ovd_scard_acct_num
,t1.latest3mon_ovd_scard_org_num	as	ltst3mon_ovd_scard_org_num
,t1.latest3mon_ovd_scard_moth_num	as	ltst3mon_ovd_scard_moth_num
,t1.latest3mon_ovd_scard_num	as	ltst3mon_ovd_scard_num
,t1.latest3mon_scard_max_ovd	as	ltst3mon_ovd_scard_longest_num
,t1.latest3mon_ovd2m_scardaccount_num	as	ltst3mon_ovd2m_scardacct_num
,t1.latest3mon_ovd2m_scard_num	as	ltst3mon_ovd2m_scard_num
,t1.latest3mon_ovd3m_scardaccount_num	as	ltst3mon_ovd3m_scardacct_num
,t1.latest3mon_ovd3m_scard_num	as	ltst3mon_ovd3m_scard_num
,t1.latest3mon_ovd4m_scardaccount_num	as	ltst3mon_ovd4m_scardacct_num
,t1.latest3mon_ovd4m_scard_num	as	ltst3mon_ovd4m_scard_num
,t1.latest6mon_ovd_scard_acct_num	as	ltst6mon_ovd_scard_acct_num
,t1.latest6mon_ovd_scard_org_num	as	ltst6mon_ovd_scard_org_num
,t1.latest6mon_ovd_scard_moth_num	as	ltst6mon_ovd_scard_moth_num
,t1.latest6mon_ovd_scard_num	as	ltst6mon_ovd_scard_num
,t1.latest6mon_scard_max_ovd	as	ltst6mon_ovd_scard_longest_num
,t1.latest6mon_ovd2m_scardaccount_num	as	ltst6mon_ovd2m_scardacct_num
,t1.latest6mon_ovd2m_scard_num	as	ltst6mon_ovd2m_scard_num
,t1.latest6mon_ovd3m_scardaccount_num	as	ltst6mon_ovd3m_scardacct_num
,t1.latest6mon_ovd3m_scard_num	as	ltst6mon_ovd3m_scard_num
,t1.latest6mon_ovd4m_scardaccount_num	as	ltst6mon_ovd4m_scardacct_num
,t1.latest6mon_ovd4m_scard_num	as	ltst6mon_ovd4m_scard_num
,t1.latest9mon_ovd_scard_acct_num	as	ltst9mon_ovd_scard_acct_num
,t1.latest9mon_ovd_scard_org_num	as	ltst9mon_ovd_scard_org_num
,t1.latest9mon_ovd_scard_moth_num	as	ltst9mon_ovd_scard_moth_num
,t1.latest9mon_ovd_scard_num	as	ltst9mon_ovd_scard_num
,t1.latest9mon_scard_max_ovd	as	ltst9mon_ovd_scard_longest_num
,t1.latest9mon_ovd2m_scardaccount_num	as	ltst9mon_ovd2m_scardacct_num
,t1.latest9mon_ovd2m_scard_num	as	ltst9mon_ovd2m_scard_num
,t1.latest9mon_ovd3m_scardaccount_num	as	ltst9mon_ovd3m_scardacct_num
,t1.latest9mon_ovd3m_scard_num	as	ltst9mon_ovd3m_scard_num
,t1.latest9mon_ovd4m_scardaccount_num	as	ltst9mon_ovd4m_scardacct_num
,t1.latest9mon_ovd4m_scard_num	as	ltst9mon_ovd4m_scard_num
,t1.latest12mon_ovd_scard_acct_num	as	ltst12mon_ovd_scard_acct_num
,t1.latest12mon_ovd_scard_org_num	as	ltst12mon_ovd_scard_org_num
,t1.latest12mon_ovd_scard_moth_num	as	ltst12mon_ovd_scard_moth_num
,t1.latest12mon_ovd_scard_num	as	ltst12mon_ovd_scard_num
,t1.latest12mon_scard_max_ovd	as	ltst12mon_ovd_scard_longest_num
,t1.latest12mon_ovd2m_scardaccount_num	as	ltst12mon_ovd2m_scardacct_num
,t1.latest12mon_ovd2m_scard_num	as	ltst12mon_ovd2m_scard_num
,t1.latest12mon_ovd3m_scardaccount_num	as	ltst12mon_ovd3m_scardacct_num
,t1.latest12mon_ovd3m_scard_num	as	ltst12mon_ovd3m_scard_num
,t1.latest12mon_ovd4m_scardaccount_num	as	ltst12mon_ovd4m_scardacct_num
,t1.latest12mon_ovd4m_scard_num	as	ltst12mon_ovd4m_scard_num
,t1.latest18mon_ovd_scard_acct_num	as	ltst18mon_ovd_scard_acct_num
,t1.latest18mon_ovd_scard_org_num	as	ltst18mon_ovd_scard_org_num
,t1.latest18mon_ovd_scard_moth_num	as	ltst18mon_ovd_scard_moth_num
,t1.latest18mon_ovd_scard_num	as	ltst18mon_ovd_scard_num
,t1.latest18mon_scard_max_ovd	as	ltst18mon_ovd_scard_longest_num
,t1.latest18mon_ovd2m_scardaccount_num	as	ltst18mon_ovd2m_scardacct_num
,t1.latest18mon_ovd2m_scard_num	as	ltst18mon_ovd2m_scard_num
,t1.latest18mon_ovd3m_scardaccount_num	as	ltst18mon_ovd3m_scardacct_num
,t1.latest18mon_ovd3m_scard_num	as	ltst18mon_ovd3m_scard_num
,t1.latest18mon_ovd4m_scardaccount_num	as	ltst18mon_ovd4m_scardacct_num
,t1.latest18mon_ovd4m_scard_num	as	ltst18mon_ovd4m_scard_num
,t1.latest24mon_ovd_scard_acct_num	as	ltst24mon_ovd_scard_acct_num
,t1.latest24mon_ovd_scard_org_num	as	ltst24mon_ovd_scard_org_num
,t1.latest24mon_ovd_scard_moth_num	as	ltst24mon_ovd_scard_moth_num
,t1.latest24mon_ovd_scard_num	as	ltst24mon_ovd_scard_num
,t1.latest24mon_scard_max_ovd	as	ltst24mon_ovd_scard_longest_num
,t1.latest24mon_ovd2m_scardaccount_num	as	ltst24mon_ovd2m_scardacct_num
,t1.latest24mon_ovd2m_scard_num	as	ltst24mon_ovd2m_scard_num
,t1.latest24mon_ovd3m_scardaccount_num	as	ltst24mon_ovd3m_scardacct_num
,t1.latest24mon_ovd3m_scard_num	as	ltst24mon_ovd3m_scard_num
,t1.latest24mon_ovd4m_scardaccount_num	as	ltst24mon_ovd4m_scardacct_num
,t1.latest24mon_ovd4m_scard_num	as	ltst24mon_ovd4m_scard_num
,t2.mth3_scard_overdue_maxmonth,t2.mth6_scard_overdue_maxmonth
,t2.mth9_scard_overdue_maxmonth,t2.mth12_scard_overdue_maxmonth
,t2.mth18_scard_overdue_maxmonth,t2.mth24_scard_overdue_maxmonth
,t3.highest_scard_overdue_permon,t3.max_scard_duration,t3.scard_overdue_months
,now() as create_time,now() as update_time,now() as etl_date
from dw_stdcard_overdue_summary t1
left join  dw_scard_contiue_overdue t2 on t1.reportno=t2.reportno
left join dw_overdue_account t3 on t1.reportno=t3.reportno


""").createOrReplaceTempView("dm_stdccard_overdue_info")

In [9]:
table_name = "dm_stdccard_overdue_info"

spark.sql("drop table if EXISTS renhang_user_profile.%s "%table_name)
spark.sql("create table renhang_user_profile.%s as select * from %s"%(table_name,table_name))

DataFrame[]