在运行dw相关表之前，首先运行下面部分以创建中间表

In [1]:
import pandas as pd
from pyspark import SparkContext,SQLContext
from pyspark.sql import SQLContext
from pyspark.sql import SparkSession
from pyspark.sql.functions import udf, col
from pyspark.sql.types import StringType
import os
import sklearn
print(os.path.abspath(os.curdir))

/home/thd/人行征信

In [2]:
spark=SparkSession \
        .builder \
        .appName('renhang_etl') \
        .master('yarn')\
        .getOrCreate()

In [3]:
#创建DW.dw_baseinfo_detail
table1 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRMESSAGEHEADER") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table1.createOrReplaceTempView("ICRMESSAGEHEADER")

table2 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRCREDITCUE") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table2.createOrReplaceTempView("ICRCREDITCUE")

table3 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRLOANCARDINFO") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table3.createOrReplaceTempView("ICRLOANCARDINFO")

table4 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRCREDITCUE") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table4.createOrReplaceTempView("ICRCREDITCUE")

table5 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRLATEST2YEAROVERDUECARD") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table5.createOrReplaceTempView("ICRLATEST2YEAROVERDUECARD")

table6 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRLATEST5YEAROVERDUEDETAIL") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table6.createOrReplaceTempView("ICRLATEST5YEAROVERDUEDETAIL")

table7 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRLATEST2YEAROVERDUE") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table7.createOrReplaceTempView("ICRLATEST2YEAROVERDUE")

table8 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRLOANINFO") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table8.createOrReplaceTempView("ICRLOANINFO")

table9 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRUNDESTORYLOANCARD") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table9.createOrReplaceTempView("ICRUNDESTORYLOANCARD")

table10 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRUNDESTORYSTANDARDLOANCARD") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table10.createOrReplaceTempView("ICRUNDESTORYSTANDARDLOANCARD")

table11 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRUNPAIDLOAN") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table11.createOrReplaceTempView("ICRUNPAIDLOAN")


table12 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICROVERDUESUMMARY") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table12.createOrReplaceTempView("ICROVERDUESUMMARY")


table13 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRFELLBACKSUMMARY") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table13.createOrReplaceTempView("ICRFELLBACKSUMMARY")


table14 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRGUARANTEE") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table14.createOrReplaceTempView("ICRGUARANTEE")


table15 = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:mysql://58.59.11.87:3306") \
    .option("dbtable", "ICR_PROD.ICRGUARANTEESUMMARY") \
    .option("user", "etl") \
    .option("password", "%TGRDJh3Hg2e4f") \
    .load()
table15.createOrReplaceTempView("ICRGUARANTEESUMMARY")

In [4]:
spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		case 
			when ordue.LASTMONTHS in ('G','Z','D') then 8 
			else ordue.LASTMONTHS 
		end as LASTMONTHS ,
		loanfo.GUARANTEETYPE,STATE,FINANCEORG
from ICRLATEST2YEAROVERDUECARD ordue
-- 只取贷记卡的信息
inner join ICRLOANCARDINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where BIZTYPE='准贷记卡' and ordue.LASTMONTHS!='C'
""").createOrReplaceTempView("temp_standcard_2yearoverdue")


spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		case 
			when ordue.LASTMONTHS in ('G','Z','D') then 8 
			else ordue.LASTMONTHS 
		end as LASTMONTHS ,
		loanfo.GUARANTEETYPE,STATE,FINANCEORG
from ICRLATEST2YEAROVERDUECARD ordue
-- 只取贷记卡的信息
inner join ICRLOANCARDINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where BIZTYPE='贷记卡' and ordue.LASTMONTHS!='C'
""").createOrReplaceTempView("temp_creditcard_2yearoverdue")


spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		ordue.LASTMONTHS,ordue.AMOUNT,loanfo.GUARANTEETYPE,STATE,FINANCEORG
from ICRLATEST5YEAROVERDUEDETAIL ordue
-- 只取贷记卡的信息
inner join ICRLOANCARDINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where month!='--'  and BIZTYPE='贷记卡'
""").createOrReplaceTempView("temp_creditcard_overdue")


spark.sql("""
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
		MONTH,
		gap_months,
		LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_creditcard_2yearoverdue
union 
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
		date_format(concat(month,'.01'),'%Y-%m'),
        gap_months,
		LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_creditcard_overdue
""").createOrReplaceTempView("temp_creditcard_5yearoverdue")



spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		case 
			when ordue.LASTMONTHS in ('G','Z','D') then 8 
			else ordue.LASTMONTHS 
		end as LASTMONTHS ,
		loanfo.GUARANTEETYPE,
		STATE,
		FINANCEORG
from ICRLATEST2YEAROVERDUE ordue
-- 只取贷款的信息
inner join ICRLOANINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where ordue.LASTMONTHS!='C'
""").createOrReplaceTempView("temp_loan_2yearoverdue")



spark.sql("""
select 
		ordue.reportno,
		ordue.ACCOUNT,
		head.QUERYTIME,
		ordue.MONTH,
		month(date_format(head.QUERYTIME,'%Y-%m-%d')) - month(date_format(concat(ordue.month,'.01'),'%Y-%m-%d')) as gap_months,
		ordue.LASTMONTHS,
		ordue.AMOUNT,
		loanfo.GUARANTEETYPE,
		STATE,FINANCEORG
from ICRLATEST5YEAROVERDUEDETAIL ordue
-- 只取贷款的信息
inner join ICRLOANINFO loanfo on ordue.reportno=loanfo.reportno and ordue.ACCOUNT=loanfo.ACCOUNT 
left join ICRMESSAGEHEADER head on ordue.reportno=head.reportno
where month!='--'
""").createOrReplaceTempView("temp_loan_overdue")




spark.sql("""
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
        MONTH,
		gap_months,
		LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_loan_2yearoverdue
union 
select 
		reportno,
		ACCOUNT,
		QUERYTIME,
		date_format(concat(month,'.01'),'%Y-%m'),gap_months,LASTMONTHS,
		GUARANTEETYPE,
		STATE,
		FINANCEORG 
from temp_loan_overdue
""").createOrReplaceTempView("temp_loan_5yearoverdue")

中间表已运行完成，spark sql 创建所需要的表

In [5]:
spark.sql("""


select head.reportno,
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_acct_num,0) end as curovd_scard_acct_num,
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_org_num,0) end as curovd_scard_org_num,	
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_amount,0) end as curovd_scard_amount,		
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_max,0) end as curovd_scard_max,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_account_num,0) end as curused_scard_account_num,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_org_num,0) end as curused_scard_org_num,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_amount,0) end as curused_scard_amount,		
case when scard.reportno is null then -9999999
	else nvl(sovdm.scard_latest_ovdue_months,-9999998) end as scard_latest_ovdue_months,	
-- 最大逾期期数	
case when scard.reportno is null then -9999999
	else nvl(latest3mon_scard_max_ovd,0) end as latest3mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_scard_max_ovd,0) end as latest6mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_scard_max_ovd,0) end as latest9mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_scard_max_ovd,0) end as latest12mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_scard_max_ovd,0) end as latest18mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_scard_max_ovd,0) end as latest24mon_scard_max_ovd,
	
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_acct_num,0) end as latest3mon_ovd_scard_acct_num,
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_org_num,0) end as latest3mon_ovd_scard_org_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_moth_num,0) end as latest3mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_num,0) end as latest3mon_ovd_scard_num,		
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd2m_scardaccount_num,0) end as latest3mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd2m_scard_num,0) end as latest3mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd3m_scardaccount_num,0) end as latest3mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd3m_scard_num,0) end as latest3mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd4m_scardaccount_num,0) end as latest3mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd4m_scard_num,0) end as latest3mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_acct_num,0) end as latest6mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_org_num,0) end as latest6mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_moth_num,0) end as latest6mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_num,0) end as latest6mon_ovd_scard_num,		
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd2m_scardaccount_num,0) end as latest6mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd2m_scard_num,0) end as latest6mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd3m_scardaccount_num,0) end as latest6mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd3m_scard_num,0) end as latest6mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd4m_scardaccount_num,0) end as latest6mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd4m_scard_num,0) end as latest6mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_acct_num,0) end as latest9mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_org_num,0) end as latest9mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_moth_num,0) end as latest9mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_num,0) end as latest9mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd2m_scardaccount_num,0) end as latest9mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd2m_scard_num,0) end as latest9mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd3m_scardaccount_num,0) end as latest9mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd3m_scard_num,0) end as latest9mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd4m_scardaccount_num,0) end as latest9mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd4m_scard_num,0) end as latest9mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_acct_num,0) end as latest12mon_ovd_scard_acct_num,		
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd_scard_org_num,0) end as latest12mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_moth_num,0) end as latest12mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_num,0) end as latest12mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd2m_scardaccount_num,0) end as latest12mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd2m_scard_num,0) end as latest12mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd3m_scardaccount_num,0) end as latest12mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd3m_scard_num,0) end as latest12mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd4m_scardaccount_num,0) end as latest12mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd4m_scard_num,0) end as latest12mon_ovd4m_scard_num,	
					
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_acct_num,0) end as latest18mon_ovd_scard_acct_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_org_num,0) end as latest18mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_moth_num,0) end as latest18mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_num,0) end as latest18mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd2m_scardaccount_num,0) end as latest18mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd2m_scard_num,0) end as latest18mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd3m_scardaccount_num,0) end as latest18mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd3m_scard_num,0) end as latest18mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd4m_scardaccount_num,0) end as latest18mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd4m_scard_num,0) end as latest18mon_ovd4m_scard_num,		
	
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_acct_num,0) end as latest24mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 	
	else nvl(latest24mon_ovd_scard_org_num,0) end as latest24mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_moth_num,0) end as latest24mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_num,0) end as latest24mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd2m_scardaccount_num,0) end as latest24mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd2m_scard_num,0) end as latest24mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd3m_scardaccount_num,0) end as latest24mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd3m_scard_num,0) end as latest24mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd4m_scardaccount_num,0) end as latest24mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd4m_scard_num,0) end as latest24mon_ovd4m_scard_num,
now() as create_time,now() as update_time,now() as etl_date	
		
from ICRMESSAGEHEADER head
left JOIN
(-- 当前处于逾期的贷记卡
select reportno,count(distinct account) as curovd_scard_acct_num,
	count(distinct FINANCEORG) as curovd_scard_org_num,
	sum(nvl(CURROVERDUEAMOUNT,0)) as curovd_scard_amount,
	max(case when substr(LATEST24STATE,-1) in ('G','Z','D') then 8 
		else substr(LATEST24STATE,-1) end) as curovd_scard_max
from ICRLOANCARDINFO 
where biztype='准贷记卡' and LATEST24STATE is not null and substr(LATEST24STATE,-1) not in('/', '#', 'N', '*','C')
group by reportno
) scfo on head.reportno=scfo.reportno
-- 当前有透支余额的准贷记卡
left join
(
select reportno,count(distinct account) as curused_scard_account_num,
	count(distinct FINANCEORG) as curused_scard_org_num,
	sum(nvl(USEDCREDITLIMITAMOUNT,0)) as curused_scard_amount
from ICRLOANCARDINFO 
where biztype='准贷记卡' and USEDCREDITLIMITAMOUNT>0 and USEDCREDITLIMITAMOUNT is not null
group by reportno
) curused on head.reportno=curused.reportno
-- 准贷记卡最近一次逾期距今月份数
left join
(
select reportno,min(nvl(gap_months,0)) as scard_latest_ovdue_months
from temp_standcard_2yearoverdue 
group by reportno
) sovdm on head.reportno=sovdm.reportno
-- 准贷记卡
left join 
(select distinct reportno from ICRLOANCARDINFO
	where biztype='准贷记卡' 
)scard  on head.reportno=scard.reportno
left join
(
	select reportno,
	-- 账户
	nvl(count(distinct latest3mon_ovd_scard_acct_num),0) as latest3mon_ovd_scard_acct_num,
	nvl(count(distinct latest6mon_ovd_scard_acct_num),0) as latest6mon_ovd_scard_acct_num,
	nvl(count(distinct latest9mon_ovd_scard_acct_num),0) as latest9mon_ovd_scard_acct_num,
	nvl(count(distinct latest12mon_ovd_scard_acct_num),0) as latest12mon_ovd_scard_acct_num,
	nvl(count(distinct latest18mon_ovd_scard_acct_num),0) as latest18mon_ovd_scard_acct_num,
	nvl(count(distinct latest24mon_ovd_scard_acct_num),0) as latest24mon_ovd_scard_acct_num,
	-- 机构
	nvl(count(distinct latest3mon_ovd_scard_org_num),0) as latest3mon_ovd_scard_org_num,
	nvl(count(distinct latest6mon_ovd_scard_org_num),0) as latest6mon_ovd_scard_org_num,
	nvl(count(distinct latest9mon_ovd_scard_org_num),0) as latest9mon_ovd_scard_org_num,
	nvl(count(distinct latest12mon_ovd_scard_org_num),0) as latest12mon_ovd_scard_org_num,
	nvl(count(distinct latest18mon_ovd_scard_org_num),0) as latest18mon_ovd_scard_org_num,
	nvl(count(distinct latest24mon_ovd_scard_org_num),0) as latest24mon_ovd_scard_org_num,
	-- 月份数
	nvl(count( distinct latest3mon_ovd_scard_moth_num),0) as latest3mon_ovd_scard_moth_num,
	nvl(count( distinct latest6mon_ovd_scard_moth_num),0) as latest6mon_ovd_scard_moth_num,
	nvl(count( distinct latest9mon_ovd_scard_moth_num),0) as latest9mon_ovd_scard_moth_num,
	nvl(count( distinct latest12mon_ovd_scard_moth_num),0) as latest12mon_ovd_scard_moth_num,
	nvl(count( distinct latest18mon_ovd_scard_moth_num),0) as latest18mon_ovd_scard_moth_num,
	nvl(count( distinct latest24mon_ovd_scard_moth_num),0) as latest24mon_ovd_scard_moth_num,
	-- 次数
	sum(latest3mon_ovd_scard_num) as latest3mon_ovd_scard_num,
	sum(latest6mon_ovd_scard_num) as latest6mon_ovd_scard_num,
	sum(latest9mon_ovd_scard_num) as latest9mon_ovd_scard_num,
	sum(latest12mon_ovd_scard_num) as latest12mon_ovd_scard_num,
	sum(latest18mon_ovd_scard_num) as latest18mon_ovd_scard_num,
	sum(latest24mon_ovd_scard_num) as latest24mon_ovd_scard_num,
	-- 最大逾期期数  
	max(nvl(latest3mon_scard_max_ovd,0)) as latest3mon_scard_max_ovd,
	max(nvl(latest6mon_scard_max_ovd,0)) as latest6mon_scard_max_ovd,
	max(nvl(latest9mon_scard_max_ovd,0)) as latest9mon_scard_max_ovd,
	max(nvl(latest12mon_scard_max_ovd,0)) as latest12mon_scard_max_ovd,
	max(nvl(latest18mon_scard_max_ovd,0)) as latest18mon_scard_max_ovd,
	max(nvl(latest24mon_scard_max_ovd,0)) as latest24mon_scard_max_ovd,
	
	nvl(count(distinct latest3mon_ovd2m_scardaccount_num),0) as latest3mon_ovd2m_scardaccount_num,
	nvl(sum(latest3mon_ovd2m_scard_num),0) as latest3mon_ovd2m_scard_num,
	nvl(count(distinct latest3mon_ovd3m_scardaccount_num),0) as latest3mon_ovd3m_scardaccount_num,
	nvl(sum(latest3mon_ovd3m_scard_num),0) as latest3mon_ovd3m_scard_num,
	nvl(count(distinct latest3mon_ovd4m_scardaccount_num),0) as latest3mon_ovd4m_scardaccount_num,
	nvl(sum(latest3mon_ovd4m_scard_num),0) as latest3mon_ovd4m_scard_num,
	
	nvl(count(distinct latest6mon_ovd2m_scardaccount_num),0) as latest6mon_ovd2m_scardaccount_num,
	nvl(sum(latest6mon_ovd2m_scard_num),0) as latest6mon_ovd2m_scard_num,
	nvl(count(distinct latest6mon_ovd3m_scardaccount_num),0) as latest6mon_ovd3m_scardaccount_num,
	nvl(sum(latest6mon_ovd3m_scard_num),0) as latest6mon_ovd3m_scard_num,
	nvl(count(distinct latest6mon_ovd4m_scardaccount_num),0) as latest6mon_ovd4m_scardaccount_num,
	nvl(sum(latest6mon_ovd4m_scard_num),0) as latest6mon_ovd4m_scard_num,
	
	nvl(count(distinct latest9mon_ovd2m_scardaccount_num),0) as latest9mon_ovd2m_scardaccount_num,
	nvl(sum(latest9mon_ovd2m_scard_num),0) as latest9mon_ovd2m_scard_num,
	nvl(count(distinct latest9mon_ovd3m_scardaccount_num),0) as latest9mon_ovd3m_scardaccount_num,
	nvl(sum(latest9mon_ovd3m_scard_num),0) as latest9mon_ovd3m_scard_num,
	nvl(count(distinct latest9mon_ovd4m_scardaccount_num),0) as latest9mon_ovd4m_scardaccount_num,
	nvl(sum(latest9mon_ovd4m_scard_num),0) as latest9mon_ovd4m_scard_num,
	
	nvl(count(distinct latest12mon_ovd2m_scardaccount_num),0) as latest12mon_ovd2m_scardaccount_num,
	nvl(sum(latest12mon_ovd2m_scard_num),0) as latest12mon_ovd2m_scard_num,
	nvl(count(distinct latest12mon_ovd3m_scardaccount_num),0) as latest12mon_ovd3m_scardaccount_num,
	nvl(sum(latest12mon_ovd3m_scard_num),0) as latest12mon_ovd3m_scard_num,
	nvl(count(distinct latest12mon_ovd4m_scardaccount_num),0) as latest12mon_ovd4m_scardaccount_num,
	nvl(sum(latest12mon_ovd4m_scard_num),0) as latest12mon_ovd4m_scard_num,
	
	nvl(count(distinct latest18mon_ovd2m_scardaccount_num),0) as latest18mon_ovd2m_scardaccount_num,
	nvl(sum(latest18mon_ovd2m_scard_num),0) as latest18mon_ovd2m_scard_num,
	nvl(count(distinct latest18mon_ovd3m_scardaccount_num),0) as latest18mon_ovd3m_scardaccount_num,
	nvl(sum(latest18mon_ovd3m_scard_num),0) as latest18mon_ovd3m_scard_num,
	nvl(count(distinct latest18mon_ovd4m_scardaccount_num),0) as latest18mon_ovd4m_scardaccount_num,
	nvl(sum(latest18mon_ovd4m_scard_num),0) as latest18mon_ovd4m_scard_num,
	
	nvl(count(distinct latest24mon_ovd2m_scardaccount_num),0) as latest24mon_ovd2m_scardaccount_num,
	nvl(sum(latest24mon_ovd2m_scard_num),0) as latest24mon_ovd2m_scard_num,
	nvl(count(distinct latest24mon_ovd3m_scardaccount_num),0) as latest24mon_ovd3m_scardaccount_num,
	nvl(sum(latest24mon_ovd3m_scard_num),0) as latest24mon_ovd3m_scard_num,
	nvl(count(distinct latest24mon_ovd4m_scardaccount_num),0) as latest24mon_ovd4m_scardaccount_num,
	nvl(sum(latest24mon_ovd4m_scard_num),0) as latest24mon_ovd4m_scard_num

	from (
		select
			reportno,
			-- 账户
			case when gap_months<3 then account else null end as latest3mon_ovd_scard_acct_num,
			case when gap_months<6 then account else null end as latest6mon_ovd_scard_acct_num,
			case when gap_months<9 then account else null end as latest9mon_ovd_scard_acct_num,
			case when gap_months<12 then account else null end as latest12mon_ovd_scard_acct_num,
			case when gap_months<18 then account else null end as latest18mon_ovd_scard_acct_num,
			case when gap_months<24 then account else null end as latest24mon_ovd_scard_acct_num,
			-- 机构
			case when gap_months<3 then FINANCEORG else null end as latest3mon_ovd_scard_org_num,
			case when gap_months<6 then FINANCEORG else null end as latest6mon_ovd_scard_org_num,
			case when gap_months<9 then FINANCEORG else null end as latest9mon_ovd_scard_org_num,
			case when gap_months<12 then FINANCEORG else null end as latest12mon_ovd_scard_org_num,
			case when gap_months<18 then FINANCEORG else null end as latest18mon_ovd_scard_org_num,
			case when gap_months<24 then FINANCEORG else null end as latest24mon_ovd_scard_org_num,
			-- 月份数
			case when gap_months<3 then month else null end as latest3mon_ovd_scard_moth_num,
			case when gap_months<6 then month else null end as latest6mon_ovd_scard_moth_num,
			case when gap_months<9 then month else null end as latest9mon_ovd_scard_moth_num,	
			case when gap_months<12 then month else null end as latest12mon_ovd_scard_moth_num,
			case when gap_months<18 then month else null end as latest18mon_ovd_scard_moth_num,	
			case when gap_months<24 then month else null end as latest24mon_ovd_scard_moth_num,
			-- 次数
			case when gap_months<3 then 1 else 0 end as latest3mon_ovd_scard_num,
			case when gap_months<6 then 1 else 0 end as latest6mon_ovd_scard_num,		
			case when gap_months<9 then 1 else 0 end as latest9mon_ovd_scard_num,		
			case when gap_months<12 then 1 else 0 end as latest12mon_ovd_scard_num,		
			case when gap_months<18 then 1 else 0 end as latest18mon_ovd_scard_num,		
			case when gap_months<24 then 1 else 0 end as latest24mon_ovd_scard_num,
			-- 最大逾期期数
			case when gap_months<3 then LASTMONTHS else null end as latest3mon_scard_max_ovd,
			case when gap_months<6 then LASTMONTHS else null end as latest6mon_scard_max_ovd,
			case when gap_months<9 then LASTMONTHS else null end as latest9mon_scard_max_ovd,
			case when gap_months<12 then LASTMONTHS else null end as latest12mon_scard_max_ovd,
			case when gap_months<18 then LASTMONTHS else null end as latest18mon_scard_max_ovd,
			case when gap_months<24 then LASTMONTHS else null end as latest24mon_scard_max_ovd,
			
			case when gap_months<3 and LASTMONTHS>=2  then account else null end as latest3mon_ovd2m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>=2  then 1 else 0 end as latest3mon_ovd2m_scard_num,
			case when gap_months<3 and LASTMONTHS>=3  then account else null end as latest3mon_ovd3m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>=3  then 1 else 0 end as latest3mon_ovd3m_scard_num,
			case when gap_months<3 and LASTMONTHS>3  then account else null end as latest3mon_ovd4m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>3  then 1 else 0 end as latest3mon_ovd4m_scard_num,
			
			case when gap_months<6 and LASTMONTHS>=2  then account else null end as latest6mon_ovd2m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>=2  then 1 else 0 end as latest6mon_ovd2m_scard_num,
			case when gap_months<6 and LASTMONTHS>=3  then account else null end as latest6mon_ovd3m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>=3  then 1 else 0 end as latest6mon_ovd3m_scard_num,
			case when gap_months<6 and LASTMONTHS>3  then account else null end as latest6mon_ovd4m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>3  then 1 else 0 end as latest6mon_ovd4m_scard_num,
	
			case when gap_months<9 and LASTMONTHS>=2  then account else null end as latest9mon_ovd2m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>=2  then 1 else 0 end as latest9mon_ovd2m_scard_num,
			case when gap_months<9 and LASTMONTHS>=3  then account else null end as latest9mon_ovd3m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>=3  then 1 else 0 end as latest9mon_ovd3m_scard_num,
			case when gap_months<9 and LASTMONTHS>3  then account else null end as latest9mon_ovd4m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>3  then 1 else 0 end as latest9mon_ovd4m_scard_num,
	
			case when gap_months<12 and LASTMONTHS>=2  then account else null end as latest12mon_ovd2m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>=2  then 1 else 0 end as latest12mon_ovd2m_scard_num,
			case when gap_months<12 and LASTMONTHS>=3  then account else null end as latest12mon_ovd3m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>=3  then 1 else 0 end as latest12mon_ovd3m_scard_num,
			case when gap_months<12 and LASTMONTHS>3  then account else null end as latest12mon_ovd4m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>3  then 1 else 0 end as latest12mon_ovd4m_scard_num,		
	
			case when gap_months<18 and LASTMONTHS>=2  then account else null end as latest18mon_ovd2m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>=2  then 1 else 0 end as latest18mon_ovd2m_scard_num,
			case when gap_months<18 and LASTMONTHS>=3  then account else null end as latest18mon_ovd3m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>=3  then 1 else 0 end as latest18mon_ovd3m_scard_num,
			case when gap_months<18 and LASTMONTHS>3  then account else null end as latest18mon_ovd4m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>3  then 1 else 0 end as latest18mon_ovd4m_scard_num,
	
			case when gap_months<24 and LASTMONTHS>=2  then account else null end as latest24mon_ovd2m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>=2  then 1 else 0 end as latest24mon_ovd2m_scard_num,
			case when gap_months<24 and LASTMONTHS>=3  then account else null end as latest24mon_ovd3m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>=3  then 1 else 0 end as latest24mon_ovd3m_scard_num,
			case when gap_months<24 and LASTMONTHS>3  then account else null end as latest24mon_ovd4m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>3  then 1 else 0 end as latest24mon_ovd4m_scard_num
			
		from temp_standcard_2yearoverdue
	)t
	group by reportno
)ovd on head.reportno=ovd.reportno


""").createOrReplaceTempView("dw_stdcard_overdue_summary")

In [8]:
spark.sql("drop table if EXISTS renhang_user_profile.dw_stdcard_overdue_summary ")
spark.sql("create table renhang_user_profile.dw_stdcard_overdue_summary as select * from dw_stdcard_overdue_summary")

DataFrame[]

In [ ]:
spark.sql("""


select head.reportno,
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_acct_num,0) end as curovd_scard_acct_num,
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_org_num,0) end as curovd_scard_org_num,	
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_amount,0) end as curovd_scard_amount,		
case when scard.reportno is null then -9999999
	else nvl(scfo.curovd_scard_max,0) end as curovd_scard_max,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_account_num,0) end as curused_scard_account_num,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_org_num,0) end as curused_scard_org_num,	
case when scard.reportno is null then -9999999
	else nvl(curused.curused_scard_amount,0) end as curused_scard_amount,		
case when scard.reportno is null then -9999999
	else nvl(sovdm.scard_latest_ovdue_months,-9999998) end as scard_latest_ovdue_months,	
-- 最大逾期期数	
case when scard.reportno is null then -9999999
	else nvl(latest3mon_scard_max_ovd,0) end as latest3mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_scard_max_ovd,0) end as latest6mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_scard_max_ovd,0) end as latest9mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_scard_max_ovd,0) end as latest12mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_scard_max_ovd,0) end as latest18mon_scard_max_ovd,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_scard_max_ovd,0) end as latest24mon_scard_max_ovd,
	
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_acct_num,0) end as latest3mon_ovd_scard_acct_num,
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_org_num,0) end as latest3mon_ovd_scard_org_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_moth_num,0) end as latest3mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest3mon_ovd_scard_num,0) end as latest3mon_ovd_scard_num,		
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd2m_scardaccount_num,0) end as latest3mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd2m_scard_num,0) end as latest3mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd3m_scardaccount_num,0) end as latest3mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd3m_scard_num,0) end as latest3mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd4m_scardaccount_num,0) end as latest3mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest3mon_ovd4m_scard_num,0) end as latest3mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_acct_num,0) end as latest6mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_org_num,0) end as latest6mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_moth_num,0) end as latest6mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest6mon_ovd_scard_num,0) end as latest6mon_ovd_scard_num,		
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd2m_scardaccount_num,0) end as latest6mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd2m_scard_num,0) end as latest6mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd3m_scardaccount_num,0) end as latest6mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd3m_scard_num,0) end as latest6mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd4m_scardaccount_num,0) end as latest6mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest6mon_ovd4m_scard_num,0) end as latest6mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_acct_num,0) end as latest9mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_org_num,0) end as latest9mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_moth_num,0) end as latest9mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest9mon_ovd_scard_num,0) end as latest9mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd2m_scardaccount_num,0) end as latest9mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd2m_scard_num,0) end as latest9mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd3m_scardaccount_num,0) end as latest9mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd3m_scard_num,0) end as latest9mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd4m_scardaccount_num,0) end as latest9mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest9mon_ovd4m_scard_num,0) end as latest9mon_ovd4m_scard_num,	
	
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_acct_num,0) end as latest12mon_ovd_scard_acct_num,		
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd_scard_org_num,0) end as latest12mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_moth_num,0) end as latest12mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest12mon_ovd_scard_num,0) end as latest12mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd2m_scardaccount_num,0) end as latest12mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd2m_scard_num,0) end as latest12mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd3m_scardaccount_num,0) end as latest12mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd3m_scard_num,0) end as latest12mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd4m_scardaccount_num,0) end as latest12mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest12mon_ovd4m_scard_num,0) end as latest12mon_ovd4m_scard_num,	
					
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_acct_num,0) end as latest18mon_ovd_scard_acct_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_org_num,0) end as latest18mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_moth_num,0) end as latest18mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest18mon_ovd_scard_num,0) end as latest18mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd2m_scardaccount_num,0) end as latest18mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd2m_scard_num,0) end as latest18mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd3m_scardaccount_num,0) end as latest18mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd3m_scard_num,0) end as latest18mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd4m_scardaccount_num,0) end as latest18mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest18mon_ovd4m_scard_num,0) end as latest18mon_ovd4m_scard_num,		
	
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_acct_num,0) end as latest24mon_ovd_scard_acct_num,	
case when scard.reportno is null then -9999999 	
	else nvl(latest24mon_ovd_scard_org_num,0) end as latest24mon_ovd_scard_org_num,
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_moth_num,0) end as latest24mon_ovd_scard_moth_num,		
case when scard.reportno is null then -9999999 
	else nvl(latest24mon_ovd_scard_num,0) end as latest24mon_ovd_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd2m_scardaccount_num,0) end as latest24mon_ovd2m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd2m_scard_num,0) end as latest24mon_ovd2m_scard_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd3m_scardaccount_num,0) end as latest24mon_ovd3m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd3m_scard_num,0) end as latest24mon_ovd3m_scard_num,	
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd4m_scardaccount_num,0) end as latest24mon_ovd4m_scardaccount_num,
case when scard.reportno is null then -9999999
	else nvl(latest24mon_ovd4m_scard_num,0) end as latest24mon_ovd4m_scard_num,
now() as create_time,now() as update_time,now() as etl_date	
		
from ICRMESSAGEHEADER head
left JOIN
(-- 当前处于逾期的贷记卡
select reportno,count(distinct account) as curovd_scard_acct_num,
	count(distinct FINANCEORG) as curovd_scard_org_num,
	sum(nvl(CURROVERDUEAMOUNT,0)) as curovd_scard_amount,
	max(case when substr(LATEST24STATE,-1) in ('G','Z','D') then 8 
		else substr(LATEST24STATE,-1) end) as curovd_scard_max
from ICRLOANCARDINFO 
where biztype='准贷记卡' and LATEST24STATE is not null and substr(LATEST24STATE,-1) not in('/', '#', 'N', '*','C')
group by reportno
) scfo on head.reportno=scfo.reportno
-- 当前有透支余额的准贷记卡
left join
(
select reportno,count(distinct account) as curused_scard_account_num,
	count(distinct FINANCEORG) as curused_scard_org_num,
	sum(nvl(USEDCREDITLIMITAMOUNT,0)) as curused_scard_amount
from ICRLOANCARDINFO 
where biztype='准贷记卡' and USEDCREDITLIMITAMOUNT>0 and USEDCREDITLIMITAMOUNT is not null
group by reportno
) curused on head.reportno=curused.reportno
-- 准贷记卡最近一次逾期距今月份数
left join
(
select reportno,min(nvl(gap_months,0)) as scard_latest_ovdue_months
from temp_standcard_2yearoverdue 
group by reportno
) sovdm on head.reportno=sovdm.reportno
-- 准贷记卡
left join 
(select distinct reportno from ICRLOANCARDINFO
	where biztype='准贷记卡' 
)scard  on head.reportno=scard.reportno
left join
(
	select reportno,
	-- 账户
	nvl(count(distinct latest3mon_ovd_scard_acct_num),0) as latest3mon_ovd_scard_acct_num,
	nvl(count(distinct latest6mon_ovd_scard_acct_num),0) as latest6mon_ovd_scard_acct_num,
	nvl(count(distinct latest9mon_ovd_scard_acct_num),0) as latest9mon_ovd_scard_acct_num,
	nvl(count(distinct latest12mon_ovd_scard_acct_num),0) as latest12mon_ovd_scard_acct_num,
	nvl(count(distinct latest18mon_ovd_scard_acct_num),0) as latest18mon_ovd_scard_acct_num,
	nvl(count(distinct latest24mon_ovd_scard_acct_num),0) as latest24mon_ovd_scard_acct_num,
	-- 机构
	nvl(count(distinct latest3mon_ovd_scard_org_num),0) as latest3mon_ovd_scard_org_num,
	nvl(count(distinct latest6mon_ovd_scard_org_num),0) as latest6mon_ovd_scard_org_num,
	nvl(count(distinct latest9mon_ovd_scard_org_num),0) as latest9mon_ovd_scard_org_num,
	nvl(count(distinct latest12mon_ovd_scard_org_num),0) as latest12mon_ovd_scard_org_num,
	nvl(count(distinct latest18mon_ovd_scard_org_num),0) as latest18mon_ovd_scard_org_num,
	nvl(count(distinct latest24mon_ovd_scard_org_num),0) as latest24mon_ovd_scard_org_num,
	-- 月份数
	nvl(count( distinct latest3mon_ovd_scard_moth_num),0) as latest3mon_ovd_scard_moth_num,
	nvl(count( distinct latest6mon_ovd_scard_moth_num),0) as latest6mon_ovd_scard_moth_num,
	nvl(count( distinct latest9mon_ovd_scard_moth_num),0) as latest9mon_ovd_scard_moth_num,
	nvl(count( distinct latest12mon_ovd_scard_moth_num),0) as latest12mon_ovd_scard_moth_num,
	nvl(count( distinct latest18mon_ovd_scard_moth_num),0) as latest18mon_ovd_scard_moth_num,
	nvl(count( distinct latest24mon_ovd_scard_moth_num),0) as latest24mon_ovd_scard_moth_num,
	-- 次数
	sum(latest3mon_ovd_scard_num) as latest3mon_ovd_scard_num,
	sum(latest6mon_ovd_scard_num) as latest6mon_ovd_scard_num,
	sum(latest9mon_ovd_scard_num) as latest9mon_ovd_scard_num,
	sum(latest12mon_ovd_scard_num) as latest12mon_ovd_scard_num,
	sum(latest18mon_ovd_scard_num) as latest18mon_ovd_scard_num,
	sum(latest24mon_ovd_scard_num) as latest24mon_ovd_scard_num,
	-- 最大逾期期数  
	max(nvl(latest3mon_scard_max_ovd,0)) as latest3mon_scard_max_ovd,
	max(nvl(latest6mon_scard_max_ovd,0)) as latest6mon_scard_max_ovd,
	max(nvl(latest9mon_scard_max_ovd,0)) as latest9mon_scard_max_ovd,
	max(nvl(latest12mon_scard_max_ovd,0)) as latest12mon_scard_max_ovd,
	max(nvl(latest18mon_scard_max_ovd,0)) as latest18mon_scard_max_ovd,
	max(nvl(latest24mon_scard_max_ovd,0)) as latest24mon_scard_max_ovd,
	
	nvl(count(distinct latest3mon_ovd2m_scardaccount_num),0) as latest3mon_ovd2m_scardaccount_num,
	nvl(sum(latest3mon_ovd2m_scard_num),0) as latest3mon_ovd2m_scard_num,
	nvl(count(distinct latest3mon_ovd3m_scardaccount_num),0) as latest3mon_ovd3m_scardaccount_num,
	nvl(sum(latest3mon_ovd3m_scard_num),0) as latest3mon_ovd3m_scard_num,
	nvl(count(distinct latest3mon_ovd4m_scardaccount_num),0) as latest3mon_ovd4m_scardaccount_num,
	nvl(sum(latest3mon_ovd4m_scard_num),0) as latest3mon_ovd4m_scard_num,
	
	nvl(count(distinct latest6mon_ovd2m_scardaccount_num),0) as latest6mon_ovd2m_scardaccount_num,
	nvl(sum(latest6mon_ovd2m_scard_num),0) as latest6mon_ovd2m_scard_num,
	nvl(count(distinct latest6mon_ovd3m_scardaccount_num),0) as latest6mon_ovd3m_scardaccount_num,
	nvl(sum(latest6mon_ovd3m_scard_num),0) as latest6mon_ovd3m_scard_num,
	nvl(count(distinct latest6mon_ovd4m_scardaccount_num),0) as latest6mon_ovd4m_scardaccount_num,
	nvl(sum(latest6mon_ovd4m_scard_num),0) as latest6mon_ovd4m_scard_num,
	
	nvl(count(distinct latest9mon_ovd2m_scardaccount_num),0) as latest9mon_ovd2m_scardaccount_num,
	nvl(sum(latest9mon_ovd2m_scard_num),0) as latest9mon_ovd2m_scard_num,
	nvl(count(distinct latest9mon_ovd3m_scardaccount_num),0) as latest9mon_ovd3m_scardaccount_num,
	nvl(sum(latest9mon_ovd3m_scard_num),0) as latest9mon_ovd3m_scard_num,
	nvl(count(distinct latest9mon_ovd4m_scardaccount_num),0) as latest9mon_ovd4m_scardaccount_num,
	nvl(sum(latest9mon_ovd4m_scard_num),0) as latest9mon_ovd4m_scard_num,
	
	nvl(count(distinct latest12mon_ovd2m_scardaccount_num),0) as latest12mon_ovd2m_scardaccount_num,
	nvl(sum(latest12mon_ovd2m_scard_num),0) as latest12mon_ovd2m_scard_num,
	nvl(count(distinct latest12mon_ovd3m_scardaccount_num),0) as latest12mon_ovd3m_scardaccount_num,
	nvl(sum(latest12mon_ovd3m_scard_num),0) as latest12mon_ovd3m_scard_num,
	nvl(count(distinct latest12mon_ovd4m_scardaccount_num),0) as latest12mon_ovd4m_scardaccount_num,
	nvl(sum(latest12mon_ovd4m_scard_num),0) as latest12mon_ovd4m_scard_num,
	
	nvl(count(distinct latest18mon_ovd2m_scardaccount_num),0) as latest18mon_ovd2m_scardaccount_num,
	nvl(sum(latest18mon_ovd2m_scard_num),0) as latest18mon_ovd2m_scard_num,
	nvl(count(distinct latest18mon_ovd3m_scardaccount_num),0) as latest18mon_ovd3m_scardaccount_num,
	nvl(sum(latest18mon_ovd3m_scard_num),0) as latest18mon_ovd3m_scard_num,
	nvl(count(distinct latest18mon_ovd4m_scardaccount_num),0) as latest18mon_ovd4m_scardaccount_num,
	nvl(sum(latest18mon_ovd4m_scard_num),0) as latest18mon_ovd4m_scard_num,
	
	nvl(count(distinct latest24mon_ovd2m_scardaccount_num),0) as latest24mon_ovd2m_scardaccount_num,
	nvl(sum(latest24mon_ovd2m_scard_num),0) as latest24mon_ovd2m_scard_num,
	nvl(count(distinct latest24mon_ovd3m_scardaccount_num),0) as latest24mon_ovd3m_scardaccount_num,
	nvl(sum(latest24mon_ovd3m_scard_num),0) as latest24mon_ovd3m_scard_num,
	nvl(count(distinct latest24mon_ovd4m_scardaccount_num),0) as latest24mon_ovd4m_scardaccount_num,
	nvl(sum(latest24mon_ovd4m_scard_num),0) as latest24mon_ovd4m_scard_num

	from (
		select
			reportno,
			-- 账户
			case when gap_months<3 then account else null end as latest3mon_ovd_scard_acct_num,
			case when gap_months<6 then account else null end as latest6mon_ovd_scard_acct_num,
			case when gap_months<9 then account else null end as latest9mon_ovd_scard_acct_num,
			case when gap_months<12 then account else null end as latest12mon_ovd_scard_acct_num,
			case when gap_months<18 then account else null end as latest18mon_ovd_scard_acct_num,
			case when gap_months<24 then account else null end as latest24mon_ovd_scard_acct_num,
			-- 机构
			case when gap_months<3 then FINANCEORG else null end as latest3mon_ovd_scard_org_num,
			case when gap_months<6 then FINANCEORG else null end as latest6mon_ovd_scard_org_num,
			case when gap_months<9 then FINANCEORG else null end as latest9mon_ovd_scard_org_num,
			case when gap_months<12 then FINANCEORG else null end as latest12mon_ovd_scard_org_num,
			case when gap_months<18 then FINANCEORG else null end as latest18mon_ovd_scard_org_num,
			case when gap_months<24 then FINANCEORG else null end as latest24mon_ovd_scard_org_num,
			-- 月份数
			case when gap_months<3 then month else null end as latest3mon_ovd_scard_moth_num,
			case when gap_months<6 then month else null end as latest6mon_ovd_scard_moth_num,
			case when gap_months<9 then month else null end as latest9mon_ovd_scard_moth_num,	
			case when gap_months<12 then month else null end as latest12mon_ovd_scard_moth_num,
			case when gap_months<18 then month else null end as latest18mon_ovd_scard_moth_num,	
			case when gap_months<24 then month else null end as latest24mon_ovd_scard_moth_num,
			-- 次数
			case when gap_months<3 then 1 else 0 end as latest3mon_ovd_scard_num,
			case when gap_months<6 then 1 else 0 end as latest6mon_ovd_scard_num,		
			case when gap_months<9 then 1 else 0 end as latest9mon_ovd_scard_num,		
			case when gap_months<12 then 1 else 0 end as latest12mon_ovd_scard_num,		
			case when gap_months<18 then 1 else 0 end as latest18mon_ovd_scard_num,		
			case when gap_months<24 then 1 else 0 end as latest24mon_ovd_scard_num,
			-- 最大逾期期数
			case when gap_months<3 then LASTMONTHS else null end as latest3mon_scard_max_ovd,
			case when gap_months<6 then LASTMONTHS else null end as latest6mon_scard_max_ovd,
			case when gap_months<9 then LASTMONTHS else null end as latest9mon_scard_max_ovd,
			case when gap_months<12 then LASTMONTHS else null end as latest12mon_scard_max_ovd,
			case when gap_months<18 then LASTMONTHS else null end as latest18mon_scard_max_ovd,
			case when gap_months<24 then LASTMONTHS else null end as latest24mon_scard_max_ovd,
			
			case when gap_months<3 and LASTMONTHS>=2  then account else null end as latest3mon_ovd2m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>=2  then 1 else 0 end as latest3mon_ovd2m_scard_num,
			case when gap_months<3 and LASTMONTHS>=3  then account else null end as latest3mon_ovd3m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>=3  then 1 else 0 end as latest3mon_ovd3m_scard_num,
			case when gap_months<3 and LASTMONTHS>3  then account else null end as latest3mon_ovd4m_scardaccount_num,
			case when gap_months<3 and LASTMONTHS>3  then 1 else 0 end as latest3mon_ovd4m_scard_num,
			
			case when gap_months<6 and LASTMONTHS>=2  then account else null end as latest6mon_ovd2m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>=2  then 1 else 0 end as latest6mon_ovd2m_scard_num,
			case when gap_months<6 and LASTMONTHS>=3  then account else null end as latest6mon_ovd3m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>=3  then 1 else 0 end as latest6mon_ovd3m_scard_num,
			case when gap_months<6 and LASTMONTHS>3  then account else null end as latest6mon_ovd4m_scardaccount_num,
			case when gap_months<6 and LASTMONTHS>3  then 1 else 0 end as latest6mon_ovd4m_scard_num,
	
			case when gap_months<9 and LASTMONTHS>=2  then account else null end as latest9mon_ovd2m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>=2  then 1 else 0 end as latest9mon_ovd2m_scard_num,
			case when gap_months<9 and LASTMONTHS>=3  then account else null end as latest9mon_ovd3m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>=3  then 1 else 0 end as latest9mon_ovd3m_scard_num,
			case when gap_months<9 and LASTMONTHS>3  then account else null end as latest9mon_ovd4m_scardaccount_num,
			case when gap_months<9 and LASTMONTHS>3  then 1 else 0 end as latest9mon_ovd4m_scard_num,
	
			case when gap_months<12 and LASTMONTHS>=2  then account else null end as latest12mon_ovd2m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>=2  then 1 else 0 end as latest12mon_ovd2m_scard_num,
			case when gap_months<12 and LASTMONTHS>=3  then account else null end as latest12mon_ovd3m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>=3  then 1 else 0 end as latest12mon_ovd3m_scard_num,
			case when gap_months<12 and LASTMONTHS>3  then account else null end as latest12mon_ovd4m_scardaccount_num,
			case when gap_months<12 and LASTMONTHS>3  then 1 else 0 end as latest12mon_ovd4m_scard_num,		
	
			case when gap_months<18 and LASTMONTHS>=2  then account else null end as latest18mon_ovd2m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>=2  then 1 else 0 end as latest18mon_ovd2m_scard_num,
			case when gap_months<18 and LASTMONTHS>=3  then account else null end as latest18mon_ovd3m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>=3  then 1 else 0 end as latest18mon_ovd3m_scard_num,
			case when gap_months<18 and LASTMONTHS>3  then account else null end as latest18mon_ovd4m_scardaccount_num,
			case when gap_months<18 and LASTMONTHS>3  then 1 else 0 end as latest18mon_ovd4m_scard_num,
	
			case when gap_months<24 and LASTMONTHS>=2  then account else null end as latest24mon_ovd2m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>=2  then 1 else 0 end as latest24mon_ovd2m_scard_num,
			case when gap_months<24 and LASTMONTHS>=3  then account else null end as latest24mon_ovd3m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>=3  then 1 else 0 end as latest24mon_ovd3m_scard_num,
			case when gap_months<24 and LASTMONTHS>3  then account else null end as latest24mon_ovd4m_scardaccount_num,
			case when gap_months<24 and LASTMONTHS>3  then 1 else 0 end as latest24mon_ovd4m_scard_num
			
		from temp_standcard_2yearoverdue
	)t
	group by reportno
)ovd on head.reportno=ovd.reportno


""").createOrReplaceTempView("dw_stdcard_overdue_summary")